USE [demoDW]
GO

BEGIN
	TRUNCATE TABLE BUYING_GROUP_D
	TRUNCATE TABLE CITY_D
	TRUNCATE TABLE CUSTOMER_CATEGORY_D
	DELETE FROM CUSTOMER_D
	TRUNCATE TABLE DELIVERY_METHOD_D
	TRUNCATE TABLE PERSON_D
	TRUNCATE TABLE [RUNS]
	TRUNCATE TABLE STATE_D
	TRUNCATE TABLE ORDER_F

	ALTER SEQUENCE SQ_PERSON RESTART WITH 1
END
GO

CREATE OR ALTER PROCEDURE TRUNCATE_DW AS
BEGIN

	TRUNCATE TABLE BUYING_GROUP_D
	TRUNCATE TABLE CITY_D
	TRUNCATE TABLE CUSTOMER_CATEGORY_D
	DELETE FROM CUSTOMER_D
	TRUNCATE TABLE DELIVERY_METHOD_D
	TRUNCATE TABLE PERSON_D
	TRUNCATE TABLE [RUNS]
	TRUNCATE TABLE STATE_D
	TRUNCATE TABLE ORDER_F

	ALTER SEQUENCE SQ_PERSON RESTART WITH 1

END
GO