USE [demoDW]
GO

CREATE SEQUENCE [dbo].[SQ_Person] 
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 CACHE 
GO

CREATE OR ALTER PROCEDURE [dbo].[GET_CHECKPOINTS]
	@RUN_NAME NVARCHAR(50)
	, @CHECKPOINT DATETIME OUTPUT
	, @NEWCHECKPOINT DATETIME OUTPUT
AS
BEGIN
	
	SET NOCOUNT ON;

	SELECT
		@CHECKPOINT = a.RUN_DT
	FROM
		(
			SELECT 
				MAX(b.RUN_DT) RUN_DT
			FROM
				(
					SELECT RUN_DT FROM [dbo].[RUNS] WHERE RUN_NAME = @RUN_NAME
					UNION
					SELECT CONVERT([datetime],'1990-01-01 00:00:00') RUN_DT
				)b
		) a

	SELECT @NEWCHECKPOINT = GETDATE()

	IF @CHECKPOINT = NULL
	BEGIN
		SET @CHECKPOINT = CONVERT([datetime],'1990-01-01 00:00:00')
	END

    RETURN
END

CREATE TABLE [dbo].[BUYING_GROUP_D](
	[BUYING_GROUP_D_ID] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_NAME] [nvarchar](50) NOT NULL,
	[GROUP_SRC_ID] [int] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[LAST_UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_BUYING_GROUP_D] PRIMARY KEY CLUSTERED 
(
	[BUYING_GROUP_D_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BUYING_GROUP_D] ADD  CONSTRAINT [DF_BUYING_GROUP_D_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[BUYING_GROUP_D] ADD  CONSTRAINT [DF_BUYING_GROUP_D_LAST_UPDATE_DATE]  DEFAULT (getdate()) FOR [LAST_UPDATE_DATE]
GO

CREATE TABLE [dbo].[CITY_D](
	[CITY_D_ID] [int] IDENTITY(1,1) NOT NULL,
	[CITY_NAME] [nvarchar](50) NOT NULL,
	[STATE_D_ID] [int] NOT NULL,
	[CITY_SRC_ID] [int] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[LAST_UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_CITY_D] PRIMARY KEY CLUSTERED 
(
	[CITY_D_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CITY_D] ADD  CONSTRAINT [DF_CITY_D_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[CITY_D] ADD  CONSTRAINT [DF_CITY_D_LAST_UPDATE_DATE]  DEFAULT (getdate()) FOR [LAST_UPDATE_DATE]
GO

CREATE TABLE [dbo].[CUSTOMER_CATEGORY_D](
	[CUSTOMER_CATEGORY_D_ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORY_NAME] [nvarchar](50) NOT NULL,
	[CATEGORY_SRC_ID] [int] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[LAST_UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_CUSTOMER_CATEGORY_D] PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_CATEGORY_D_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CUSTOMER_CATEGORY_D] ADD  CONSTRAINT [DF_CUSTOMER_CATEGORY_D_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[CUSTOMER_CATEGORY_D] ADD  CONSTRAINT [DF_CUSTOMER_CATEGORY_D_LAST_UPDATE_DATE]  DEFAULT (getdate()) FOR [LAST_UPDATE_DATE]
GO

CREATE TABLE [dbo].[CUSTOMER_D](
	[CUSTOMER_D_ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER_SRC_ID] [int] NOT NULL,
	[CUSTOMER_NAME] [nvarchar](100) NOT NULL,
	[BILL_TO_CUSTOMER_D_ID] [int] NOT NULL,
	[CUSTOMER_CATEGORY_D_ID] [int] NOT NULL,
	[BUYING_GROUP_D_ID] [int] NOT NULL,
	[PRIMARY_CONTACT_PERSON_D_ID] [int] NOT NULL,
	[PRIMARY_CONTACT_PERSON_CUR_D_ID] [int] NOT NULL,
	[ALT_CONTACT_PERSON_D_ID] [int] NOT NULL,
	[ALT_CONTACT_PERSON_CUR_D_ID] [int] NOT NULL,
	[DELIVERY_METHOD_D_ID] [int] NOT NULL,
	[DELIVERY_CITY_D_ID] [int] NOT NULL,
	[POSTAL_CITY_D_ID] [int] NOT NULL,
	[CREDIT_LIMIT] [decimal](18, 2) NULL,
	[OPENED_DATE] [date] NOT NULL,
	[DISCOUNT_PERCENT] [decimal](18, 3) NULL,
	[IS_STMT_SENT] [bit] NOT NULL,
	[IS_CREDIT_HOLD] [bit] NOT NULL,
	[PAYMENT_DAYS] [int] NOT NULL,
	[PHONE_NUMBER] [nvarchar](20) NOT NULL,
	[FAX_NUMBER] [nvarchar](20) NOT NULL,
	[DELIVERY_RUN] [nvarchar](5) NULL,
	[RUN_POSITION] [nvarchar](5) NULL,
	[WEBSITE_URL] [nvarchar](256) NOT NULL,
	[DELIVERY_ADDRESS_LINE_1] [nvarchar](60) NOT NULL,
	[DELIVERY_ADDRESS_LINE_2] [nvarchar](60) NULL,
	[DELIVERY_POSTAL_CODE] [nvarchar](10) NOT NULL,
	[DELIVERY_LOCATION] [geography] NULL,
	[POSTAL_ADDRESS_LINE_1] [nvarchar](60) NOT NULL,
	[POSTAL_ADDRESS_LINE_2] [nvarchar](60) NULL,
	[POSTAL_ADDRESS_CODE] [nchar](10) NULL,
	[SysStartTime] [datetime2](0) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEndTime] [datetime2](0) GENERATED ALWAYS AS ROW END NOT NULL,
 CONSTRAINT [PK_CUSTOMER_D] PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_D_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [History].[CUSTOMER_D] )
)
GO

ALTER TABLE [dbo].[CUSTOMER_D] ADD  CONSTRAINT [DF_SysStart_CUSTOMER_D]  DEFAULT (sysutcdatetime()) FOR [SysStartTime]
GO

ALTER TABLE [dbo].[CUSTOMER_D] ADD  CONSTRAINT [DF_SysEnd_CUSTOMER_D]  DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) FOR [SysEndTime]
GO

CREATE TABLE [dbo].[DELIVERY_METHOD_D](
	[DELIVERY_METHOD_D_ID] [int] IDENTITY(1,1) NOT NULL,
	[METHOD_NAME] [nvarchar](50) NOT NULL,
	[METHOD_SRC_ID] [int] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[LAST_UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_DELIVERY_METHOD_D] PRIMARY KEY CLUSTERED 
(
	[DELIVERY_METHOD_D_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DELIVERY_METHOD_D] ADD  CONSTRAINT [DF_DELIVERY_METHOD_D_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[DELIVERY_METHOD_D] ADD  CONSTRAINT [DF_DELIVERY_METHOD_D_LAST_UPDATE_DATE]  DEFAULT (getdate()) FOR [LAST_UPDATE_DATE]
GO

CREATE TABLE [dbo].[PERSON_D](
	[PERSON_D_ID] [int] IDENTITY(1,1) NOT NULL,
	[PERSON_UNQ_D_ID] [int] NOT NULL,
	[PERSON_SRC_ID] [int] NOT NULL,
	[FULL_NAME] [nvarchar](50) NOT NULL,
	[PREFERRED_NAME] [nvarchar](50) NOT NULL,
	[IS_PERMITTED_TO_LOGON] [bit] NOT NULL,
	[LOGON_NAME] [nvarchar](50) NULL,
	[IS_EXTERNAL_LOGON_PROVIDER] [bit] NOT NULL,
	[IS_SYSTEM_USER] [bit] NOT NULL,
	[IS_EMPLOYEE] [bit] NOT NULL,
	[IS_SALESPERSON] [bit] NOT NULL,
	[PHONE_NUMBER] [nvarchar](20) NULL,
	[FAX_NUMBER] [nvarchar](20) NULL,
	[EMAIL_ADDRESS] [nvarchar](256) NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[LAST_UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_PERSON_D] PRIMARY KEY CLUSTERED 
(
	[PERSON_D_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RUNS](
	[RUN_ID] [int] IDENTITY(1,1) NOT NULL,
	[RUN_NAME] [nvarchar](50) NOT NULL,
	[RUN_DT] [datetime] NOT NULL,
	[SOURCE_COLUMNS] [int] NOT NULL,
	[ROWS_INS] [int] NOT NULL,
	[ROWS_DEL] [int] NOT NULL,
	[ROWS_UPD] [int] NOT NULL,
	[ROWS_SKIP] [int] NOT NULL,
	[LOAD_VALID]  AS (case when [SOURCE_COLUMNS]=((([ROWS_INS]+[ROWS_DEL])+[ROWS_UPD])+[ROWS_SKIP]) then 'YES' else 'NO' end),
 CONSTRAINT [PK_RUNS] PRIMARY KEY CLUSTERED 
(
	[RUN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RUNS] ADD  CONSTRAINT [DF_RUNS_SOURCE_COLUMNS]  DEFAULT ((0)) FOR [SOURCE_COLUMNS]
GO

ALTER TABLE [dbo].[RUNS] ADD  CONSTRAINT [DF_RUNS_ROWS_INS]  DEFAULT ((0)) FOR [ROWS_INS]
GO

ALTER TABLE [dbo].[RUNS] ADD  CONSTRAINT [DF_RUNS_ROWS_DEL]  DEFAULT ((0)) FOR [ROWS_DEL]
GO

ALTER TABLE [dbo].[RUNS] ADD  CONSTRAINT [DF_RUNS_ROWS_UPD]  DEFAULT ((0)) FOR [ROWS_UPD]
GO

ALTER TABLE [dbo].[RUNS] ADD  CONSTRAINT [DF_RUNS_ROWS_SKIP]  DEFAULT ((0)) FOR [ROWS_SKIP]
GO

CREATE TABLE [dbo].[STATE_D](
	[STATE_D_ID] [int] IDENTITY(1,1) NOT NULL,
	[STATE_SRC_ID] [int] NOT NULL,
	[STATE_CODE] [nvarchar](50) NOT NULL,
	[STATE_NAME] [nvarchar](50) NOT NULL,
	[SALES_TERRITORY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[LAST_UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_STATE_D] PRIMARY KEY CLUSTERED 
(
	[STATE_D_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STATE_D] ADD  CONSTRAINT [DF_STATE_D_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[STATE_D] ADD  CONSTRAINT [DF_STATE_D_LAST_UPDATE_DATE]  DEFAULT (getdate()) FOR [LAST_UPDATE_DATE]
GO

CREATE TABLE [dbo].[ORDER_F](
	[ORDER_F_ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_SRC_ID] [int] NOT NULL,
	[CUSTOMER_D_ID] [int] NOT NULL,
	[SALES_PERSON_UNQ_D_ID] [int] NOT NULL,
	[PICKED_PERSON_UNQ_D_ID] [int] NULL,
	[CONTACT_PERSON_UNQ_D_ID] [int] NOT NULL,
	[ORDER_DATE] [date] NOT NULL,
	[EXPECTED_DELIVERY_DATE] [date] NOT NULL,
	[PONUMBER] [nvarchar](20) NULL,
	[IS_UNDERSUPPLY_BACKORDER] [bit] NOT NULL,
	[PICKING_COMPLETED] [datetime2](7) NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[LAST_UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_ORDER_F] PRIMARY KEY CLUSTERED 
(
	[ORDER_F_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORDER_F] ADD  CONSTRAINT [DF_ORDER_F_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[ORDER_F] ADD  CONSTRAINT [DF_ORDER_F_LAST_UPDATE_DATE]  DEFAULT (getdate()) FOR [LAST_UPDATE_DATE]
GO

CREATE TABLE [dbo].[STAGE_PERSON_D](
	[PERSON_D_ID] [int] IDENTITY(1,1) NOT NULL,
	[PERSON_UNQ_D_ID] [int] NOT NULL,
	[PERSON_SRC_ID] [int] NOT NULL,
	[FULL_NAME] [nvarchar](50) NOT NULL,
	[PREFERRED_NAME] [nvarchar](50) NOT NULL,
	[IS_PERMITTED_TO_LOGON] [bit] NOT NULL,
	[LOGON_NAME] [nvarchar](50) NULL,
	[IS_EXTERNAL_LOGON_PROVIDER] [bit] NOT NULL,
	[IS_SYSTEM_USER] [bit] NOT NULL,
	[IS_EMPLOYEE] [bit] NOT NULL,
	[IS_SALESPERSON] [bit] NOT NULL,
	[PHONE_NUMBER] [nvarchar](20) NULL,
	[FAX_NUMBER] [nvarchar](20) NULL,
	[EMAIL_ADDRESS] [nvarchar](256) NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[LAST_UPDATE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_STAGE_PERSON_D] PRIMARY KEY CLUSTERED 
(
	[PERSON_D_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STAGE_PERSON_D] ADD  CONSTRAINT [DF_STAGE_PERSON_D_PERSON_UNQ_D_ID]  DEFAULT (NEXT VALUE FOR [SQ_Person]) FOR [PERSON_UNQ_D_ID]
GO

ALTER TABLE [dbo].[BUYING_GROUP_D] ADD  CONSTRAINT [DF_STAGE_PERSON_D_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[BUYING_GROUP_D] ADD  CONSTRAINT [DF_STAGE_PERSON_D_LAST_UPDATE_DATE]  DEFAULT (getdate()) FOR [LAST_UPDATE_DATE]
GO